<%@ Page Title="" Language="C#" MasterPageFile="~/AdminPage.master" AutoEventWireup="true" CodeFile="Edit_Item.aspx.cs" Inherits="Edit_Item" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AdminTools" Runat="Server">
    <div>
        <table style="width: 100%; font-family:'Segoe UI'">
            <tr>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td style="text-align:center;">
                    <asp:TextBox ID="search" runat="server" MaxLength="40" Width="50%" Height="40px"
                        placeholder="Search by typing the product or brand name"></asp:TextBox>
                &nbsp;<asp:Button ID="bSearch" runat="server" CssClass="button" OnClick="bSearch_Click" Text="Search" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="P_Name" DataSourceID="SqlDataSource1" AutoGenerateColumns="False" CellPadding="5" CellSpacing="10" HorizontalAlign="Center">
                        <Columns>
                            <asp:BoundField DataField="P_Name" HeaderText="Product" ReadOnly="True" SortExpression="P_Name" />
                            <asp:BoundField DataField="Category" HeaderText="Category" SortExpression="Category" />
                            <asp:BoundField DataField="Image" HeaderText="Image" SortExpression="Image" />
                            <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                            <asp:BoundField DataField="P_Details" HeaderText="Details" SortExpression="P_Details" />
                        </Columns>
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [Product_Tb]" UpdateCommand="UPDATE Product_Tb SET P_Name=@P_Name, Category=@Category, Image=@Image, Price=@Price, P_Details=@P_Details WHERE P_Name=@P_Name" DeleteCommand="DELETE FROM Product_Tb WHERE P_Name=@P_Name" ></asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
            </tr>
        </table>
    </div>
</asp:Content>

